imports:
    - php

tools:
    external_code_coverage: true

checks:
    php:
        excluded_dependencies:
            - gpslab/cqrs
            - gpslab/domain-event
            - symfony/serializer
            - phpunit/phpunit
            - scrutinizer/ocular
            - satooshi/php-coveralls
